name: Build and Test

on: [push, pull_request]

env:
  BMI_VERSION: 2_0

jobs:
  build-test:

    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
 
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: testing
          create-args: >-
            cmake
            fortran-compiler

      - name: Install VS (Windows)
        if: matrix.os == 'windows-latest'
        run: micromamba install cxx-compiler vs2019_win-64

      # This is a no-op on Linux and macOS
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Make cmake build directory
        run: cmake -E make_directory build

      - name: Configure cmake (Unix)
        if: matrix.os != 'windows-latest'
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release

      - name: Configure cmake (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX% -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --target install --config Release

      - name: Test (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          test -f $CONDA_PREFIX/include/bmif_$BMI_VERSION.mod
          test -s $CONDA_PREFIX/lib/libbmif.a

      - name: Test (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: test -h $CONDA_PREFIX/lib/libbmif.so

      - name: Test (macOS)
        if: matrix.os == 'macos-latest'
        run: test -h $CONDA_PREFIX/lib/libbmif.dylib

      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ${{ github.workspace }}/build
        run: |
          if ( -not ( Test-Path -Path %CONDA_PREFIX%\lib\libbmif.a ) ){ exit 1 }
          if ( -not ( Test-Path -Path %CONDA_PREFIX%\lib\libbmif_win.dll.a ) ){ exit 1 }
          if ( -not ( Test-Path -Path %CONDA_PREFIX%\bin\libbmif_win.dll ) ){ exit 1 }
          if ( -not ( Test-Path -Path %CONDA_PREFIX%\include\bmif_${{ env.BMI_VERSION }}.mod ) ){ exit 1 }
