name: Build and Test

on: [push, pull_request, workflow_call]

env:
  BMI_VERSION: 2_0

jobs:

  build-test-windows:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: windows-latest

    env:
      LIBRARY_PREFIX: $env:CONDA_PREFIX\Library

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: testing
          create-args: >-
            cmake
            cxx-compiler
          init-shell: >-
            powershell

      - name: Make cmake build directory
        run: cmake -E make_directory build

      - name: Configure, build, and install
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX="${{ env.LIBRARY_PREFIX }}" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --target install --config Release

      - name: Check (for humans)
        working-directory: ${{ github.workspace }}/build
        run: |
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\libbmif.a
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\libbmif_win.dll.a
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\bin\libbmif_win.dll
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\include\bmif_${{ env.BMI_VERSION }}.mod

      - name: Test (for machines)
        working-directory: ${{ github.workspace }}/build
        run: |
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\libbmif.a ) ){ exit 1 }
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\libbmif_win.dll.a ) ){ exit 1 }
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\bin\libbmif_win.dll ) ){ exit 1 }
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\include\bmif_${{ env.BMI_VERSION }}.mod ) ){ exit 1 }
