name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    env:
      BMI_VERSION: 2_0

    strategy:
      matrix:
        os: [windows-latest]
        build-type: [Release]

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: testing
          create-args: >-
            cmake
            fortran-compiler
            cxx-compiler
            vs2019_win-64

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Make cmake build directory
        run: cmake -E make_directory build

      - name: Configure cmake
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX% -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --target install --config ${{ matrix.build-type }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: |
          Test-Path -Path "%LIBRARY_INC%\\bmif_%BMI_VERSION%.mod"
          Test-Path -Path "%CONDA_PREFIX%/include/bmif_%BMI_VERSION%.mod"
          Test-Path -Path "D:/a/bmi-fortran/bmi-fortran/build/%CONDA_PREFIX%/include/bmif_2_0.mod"
          if ( -not ( Test-Path -Path "%LIBRARY_INC%\\bmif_%BMI_VERSION%.mod" ) ){ exit 1 }

# D:/a/bmi-fortran/bmi-fortran/build/%CONDA_PREFIX%/lib/libbmif.a
# D:/a/bmi-fortran/bmi-fortran/build/%CONDA_PREFIX%/lib/libbmif_win.dll.a
# D:/a/bmi-fortran/bmi-fortran/build/%CONDA_PREFIX%/bin/libbmif_win.dll
# D:/a/bmi-fortran/bmi-fortran/build/%CONDA_PREFIX%/include/bmif_2_0.mod
# D:/a/bmi-fortran/bmi-fortran/build
